[package]
name = "finite-field-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec = "0.5.0"
ark-ed-on-bn254 = "0.5.0"
ark-ff = "0.5.0"
ark-poly = "0.5.0"
ark-std = "0.5.0"
ark-test-curves = { version = "0.5.0", features = ["bls12_381_curve"] }
itertools = "0.14.0"
